AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.7
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'bin/*'
    - config.ru
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
